export default function SettingsPage() {
  return (
    <div>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
      <h1>GENERAL</h1>
    </div>
  )
}
