import { MantineColor, MantineSize } from '@mantine/core'
import { Table } from '@tanstack/react-table'
import { ReactNode } from 'react'

export type DataTablePaginationProps = {
  /**
   * Current page number (1-based); if provided, a pagination component is shown
   */
  page: number

  /**
   * Callback fired after change of each page
   */
  onPageChange: (page: number) => void

  /**
   * Total number of records in the dataset
   */
  totalRecords?: number

  /**
   * Number of records per page
   */
  recordsPerPage: number

  /**
   * Pagination component size; defaults to `sm`
   */
  paginationSize?: MantineSize

  /**
   * Pagination text; defaults to ```({ from, to, totalRecords }) => `${from}-${to}/${totalRecords}`
   * ```
   */
  paginationText?: (options: {
    from: number
    to: number
    totalRecords: number
  }) => ReactNode
}

export type DataTableContextMenuItemProps =
  | {
      /**
       * Unique item key
       */
      key: string
    } & (
      | {
          /**
           * If true, insert an actions divider
           */
          divider: true
          icon?: never
          title?: never
          color?: never
          hidden?: never
          disabled?: never
          onClick?: never
        }
      | {
          divider?: never
          /**
           * Item icon
           */
          icon?: ReactNode

          /**
           * Item title; if not present, one will be generated by "humanizing"
           * the provided item key
           * (i.e. `viewRecord` -> `View record`)
           */
          title?: ReactNode

          /**
           * Item color
           */
          color?: MantineColor

          /**
           * if true, the menu item will not be shown
           */
          hidden?: boolean

          /**
           * if true, the menu item will be disabled
           */
          disabled?: boolean

          /**
           * Function to call when the menu item is clicked
           */
          onClick: () => void
        }
    )

export type DataGridColumn<T> = {
  /**
   * Column accessor; you can use dot-notation for nested objects property drilling
   * (i.e. `department.name` or `department.company.name`)
   */
  accessor: string

  /**
   * Optional column header title; if not present, one will be generated by "humanizing"
   * the provided column accessor
   * (i.e. `firstName` -> `First name`; `user.firstName` -> `User first name`)
   */
  title?: ReactNode

  render?: (record: T) => ReactNode

  textAlignment?: 'left' | 'right' | 'center'
}

export type DataGridProps<T> = {
  table: Table<T>
  onRowClick?: (record: T) => void
  rowContextMenu?: {
    /**
     * Context menu trigger; defaults to `rightClick` for classic behavior
     */
    trigger?: 'rightClick' | 'click'

    /**
     * Menu z-index; defaults to `3`
     */
    zIndex?: number

    /**
     * Boolean or function accepting the current record as parameter returning boolean;
     * if true, the menu will not be shown
     */
    hidden?: boolean | ((record: T) => boolean)

    /**
     * A function returning the row menu items for the current record
     */
    items: (record: T) => DataTableContextMenuItemProps[]
  }
  onPageChange?: (page: number) => void
} & DataTablePaginationProps
